version: "3.8"

services:
  db:
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1q2w3e4r
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  server:
    build: .
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; 
             python manage.py makemigrations --no-input
             && python manage.py migrate --no-input
             && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: 'False'

volumes:
    postgres_data: