version: "3.8"

services:
  db:
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1q2w3e4r
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; 
             python manage.py makemigrations --no-input
             && python manage.py migrate --no-input
             && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DEBUG: 'False'

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/app
    depends_on:
      - web

volumes:
    postgres_data: