# Generated by Django 4.2.6 on 2023-10-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_tag_alter_comment_options_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/placeholder.jpg', upload_to='images'),
        ),
    ]
