# Generated by Django 4.2.6 on 2023-10-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/images/placeholder.jpg', upload_to='images'),
        ),
    ]
